image:
  file: .gitpod.Dockerfile

# Open ports for the Django development server and Ngrok
ports:
  - port: 8000
    onOpen: open-preview
  - port: 4040
    onOpen: open-browser

# Install and start Ngrok and Django
tasks:
  - init: |
      # Install Ngrok
      wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
      unzip ngrok-stable-linux-amd64.zip
      chmod +x ngrok
      sudo mv ngrok /usr/local/bin
      
      # Set Ngrok authentication token
      ./ngrok authtoken 2MUZUXAAGiAm5owRnbgreBhCOQc_7iD2Q89BYCKxYDugsdmw6

      # Start Django project
      cd mainproject
      python manage.py runserver 0.0.0.0:8000 &

      # Start Ngrok on custom domain
      ./ngrok http -hostname=dev.gather.day 8000
    name: Ngrok and Django
    command: bash
