apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-django-app
  labels:
    app: my-django-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-django-app
  template:
    metadata:
      labels:
        app: my-django-app
    spec:
      containers:
      - name: my-django-app
        image: docker.io/davidable29/my-django-app:latest #add this here? 
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: mainproject.settings
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

