# dev-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: myproject-dev-service
spec:
  selector:
    app: myproject-dev
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8000
